Add variable query for distinct event property values
factrylabs/factry-historian-datasource pull request #28
Opened 2024-11-05 11:49 UTC by vereecw

2024-11-12 14:03 UTC, diericd requested changes

2024-11-12 14:03 UTC, diericd commented on src/variable_support.ts
> +      case 'SimpleEventTypePropertyValuesQuery': {
PropertyValuesQuery

2024-11-12 14:03 UTC, diericd commented on src/types.ts
> +  type: 'SimpleEventTypePropertyValuesQuery'
use constants

2024-11-12 14:03 UTC, diericd commented on src/types.ts
> +  | SimpleEventTypePropertyValuesVariableQuery
PropertyValuesVariableQuery

2024-11-12 14:03 UTC, diericd commented on src/QueryEditor/Events.tsx
> +
jumping a bit to far ahead here

```suggestion
 const getValueFilterOperators = (): KnownOperator[] => {
    const basicOperators: KnownOperator[] = ['=', '!=', '<', '<=', '>', '>=']
    const v72Operators: KnownOperator[] = ['~', '!~', 'IN', 'NOT IN']
    
    if (props.historianInfo && !semverCompare(props.historianInfo.Version, 'v7.2.0')) {
        return [...basicOperators, ...v72Operators]
    }
    return basicOperators
}

```

2024-11-12 14:03 UTC, diericd commented on src/QueryEditor/Events.tsx
> +    if (props.historianInfo && !semverCompare(props.historianInfo.Version, 'v7.3.0')) {
can you rework the semverCompare to reflect the standard compare function in javascript?  

function compare(a, b){return a — b}
1. Return greater than 0 if a is greater than b
2. Return 0 if a equals b
3. Return less than 0 if a is less than b

2024-11-12 14:03 UTC, diericd commented on pkg/api/util.go
> +}
this is a lot of similar code in this file. Do you think you can improve on this?

2024-11-12 14:03 UTC, diericd commented on pkg/api/util.go
> +	return assetUUIDSet, nil
you could use the code from historian:

// ByUUID converts a slice of objects with a UUID field to a map with the UUID as key
func ByUUID[T Model](arr []T) map[uuid.UUID]T {
	return ByFunc(arr, func(obj T) (uuid.UUID, bool) {
		return obj.GetUUID(), true
	})
}

2024-11-12 14:03 UTC, diericd commented on pkg/api/historian.go
> +		Limit:          math.MaxInt32,
```suggestion
		Limit:         0,
```

2024-11-12 14:05 UTC, diericd commented on src/QueryEditor/Events.tsx
> +    if (props.historianInfo && !semverCompare(props.historianInfo.Version, 'v7.3.0')) {
I'll put this in the other MR

2024-11-13 15:08 UTC, vereecw commented on pkg/api/util.go
> +}
I think it wont make it much more readable

2024-11-14 13:31 UTC, diericd requested changes

2024-11-14 13:31 UTC, diericd commented on pkg/api/util.go
> +}
I think code deduplication trumps readability in this case.



```suggestion
func filterItems[T any](items []T, searchValue string, matchFuncs ...func(T) string) []T {
    filteredItems := make([]T, 0, len(items))
    if len(searchValue) == 0 {
        return filteredItems // Early exit for empty search
    }

    var re *regexp.Regexp
    if strings.HasPrefix(searchValue, "/") && strings.HasSuffix(searchValue, "/") {
        if len(searchValue) > 2 {
            pattern := searchValue[1 : len(searchValue)-1]
            var err error
            re, err = regexp.Compile(pattern)
            if err != nil {
                return filteredItems
            }
        } else {
            return filteredItems
        }
    }

    
    for _, item := range items {
        for _, matchFunc := range matchFuncs {
            if (re != nil && re.MatchString(matchFunc(item))) || (re == nil && matchFunc(item) == searchValue) {
                filteredItems = append(filteredItems, item)
                break
            }
        }
    }
    return filteredItems
}

func filterAssetUUIDs(assets []schemas.Asset, searchValue string) []schemas.Asset {
    return filterItems(assets, searchValue, 
        func(asset schemas.Asset) string { return asset.AssetPath },
        func(asset schemas.Asset) string { return asset.UUID.String() })
}

func filterEventTypeUUIDs(eventTypes []schemas.EventType, searchValue string) []schemas.EventType {
    return filterItems(eventTypes, searchValue, 
        func(eventType schemas.EventType) string { return eventType.Name },
        func(eventType schemas.EventType) string { return eventType.UUID.String() })
}
```

2024-11-14 14:12 UTC, diericd requested changes

2024-11-14 14:12 UTC, diericd commented on src/CustomVariableEditor/VariableEditor.tsx
> +    if (historianInfo !== undefined && !semverCompare(historianInfo.Version, 'v7.3.0')) {
whoooo major  jump here.

2024-11-14 14:33 UTC, diericd commented
Add value filters

<img width="472" alt="image" src="https://github.com/user-attachments/assets/9b4e9f4e-aaee-473b-9043-7ecc72c20adb">

2024-11-14 15:29 UTC, diericd requested changes
It is missing a time filter

2024-11-14 16:10 UTC, diericd commented on src/CustomVariableEditor/PropertyValuesFilter.tsx
> +        ScopedVars: {},
what is this doing here?

2024-11-14 16:13 UTC, diericd requested changes

2024-11-14 16:13 UTC, diericd commented on pkg/datasource/resource_handler.go
> +		return resource.SendJSON(sender, o)
This is missing the time filter

2024-11-15 08:18 UTC, diericd requested changes

2024-11-15 08:18 UTC, diericd commented on src/variable_support.ts
> +        }
this solved the thingy, don't know if we need to do this in other places in the file



const filter = {
          ...(JSON.parse(JSON.stringify(request.targets[0].filter)) as EventTypePropertiesValuesFilter),
          ScopedVars: request.scopedVars,
        }

2024-11-15 14:46 UTC, diericd approved these changes

2024-11-15 14:53 UTC, merged