Check validity of regexes before sending them to the frontend + tooltip for invalid regex
factrylabs/factry-historian-datasource pull request #36
Opened 2024-11-26 13:05 UTC by vdpoora

https://dev.azure.com/factry/Historian/_workitems/edit/24117

2024-11-26 16:01 UTC, vereecw requested changes

2024-11-26 16:01 UTC, vereecw commented on src/components/util/MeasurementSelect.tsx
> +import React, { ChangeEvent, useState } from 'react';
no ';' please, thank you

2024-11-26 16:01 UTC, vereecw commented on src/util/util.ts
> +}
so this string is a regex? "/"

2024-11-26 16:01 UTC, vereecw commented on src/variable_support.ts
> +        if (!filter || filter.Keyword === '/') {
not sure this check is still needed I think the historian wont see this as a regex anymore. But might still be good for older historian versions maybe

2024-11-26 16:01 UTC, vereecw commented on src/components/util/MaybeRegexInput.tsx
> +    }
```suggestion
    let valid = false
    if (isRegex(keyword)) {
      if (isValidRegex(keyword)) {
        setError(undefined)
        valid = true
      } else {
        setError('Invalid regex')
      }
    } else {
      setError(undefined)
      valid = true
    }
```

2024-11-26 16:01 UTC, vereecw commented on src/CustomVariableEditor/MeasurementFilter.tsx
> +          />
not sure anymore but I thought with the toggle that the '/' were not needed anymore here and that they were added automatically later. Might be misremembering though

2024-11-26 16:12 UTC, vereecw commented
still does the request sometimes even though the regex is invalid?

2024-11-27 08:20 UTC, vdpoora commented
> still does the request sometimes even though the regex is invalid? When you enter an invalid regex for assets/measurement in the regular query editor en manually press the refresh button

Don't think I can easily prevent that, might be a bigger refactor than it is worth

2024-11-28 07:24 UTC, vereecw commented on src/variable_support.ts
> +        console.log(filter)
remove console.log

2024-11-29 09:26 UTC, vereecw approved these changes

2024-11-29 10:25 UTC, merged